spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/universitydb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 5252
  servlet:
    session:
      timeout: 2m

some:
  value: false